### ISSUE TITLE
第6回のTable of Contentsが一番下に表示される

### ISSUE THREAD

**Issue by ShumpeiSasaki** [ethereum-terakoya/ethereum-terakoya.github.io#15]
第6回のTable of Contentsが一番下に表示される。
![image](https://user-images.githubusercontent.com/50473455/96432650-f6ee8b00-123f-11eb-9b07-c814ea5d3e07.png)

**Comment by ShumpeiSasaki** [comment]
@hi-hirokona 完了次第、清水さん(@Keita-Shimizu135 )にassignして下さい。

**Comment by hi-hirokona** [comment]
@ShumpeiSasaki 
承知しました。一点ご確認なのですが、今回マージ分の公開領域へのアップロードはお済みでしょうか？
アップ済みでしたらすみません。
ざっと見ただけなのですが、修正に追記したCSSの反映が確認出来ないようでして。

以上、とりいそぎ。
明日の作業は開発環境と公開領域の差異がどこで発生しているのかの検証から始めたいと思います。

**Comment by ShumpeiSasaki** [comment]
@hi-hirokona 公開領域へのアップも中原さんにお願いできますか?

**Comment by hi-hirokona** [comment]
@ShumpeiSasaki
いったんサーバ情報共有いただいてアクセス試してからでないと、ちょっと判断出来かねます。
外部からもアクセス可能なら可能かと思いますが・・・！

**Comment by hi-hirokona** [comment]
一旦記事の修正・追加の作業を進めておきます。

**Comment by kazuakiishiguro** [comment]
@hi-hirokona 
サーバーはなくて、github上でホストしているのでそのままクライアントからdeploy可能です。

deploy方法：
https://github.com/ethereum-terakoya/ethereum-terakoya.github.io#deploy

**Comment by hi-hirokona** [comment]
@kazuakiishiguro なるほどです。サーバーレスなのですね。
ご返答ありがとうございます。
ちょっと今新規分の記事追加をしていますのでそちら終わってから確認します。

**Comment by hi-hirokona** [comment]
@ShumpeiSasaki @kazuakiishiguro 
ちゃんと書いてくださっているのにお手間をおかけしすみません。
前回私が作業時に途中からなぜかデプロイではなくビルドしていたようです。
大変失礼しました。
記事が上がったのを確認できたので、このあと問題なさそうならアサイニー変更します。

**Comment by Keita-Shimizu135** [comment]
位置については確認できましたが、3.1のあとに3.2となり、また3.1に戻っています。ご確認いただけないでしょうか。
ページ内リンクが無効のようです。

**Comment by hi-hirokona** [comment]
@Keita-Shimizu135
該当箇所確認できましたので修正しました。
ご確認よろしくお願いいたします。

**Comment by Keita-Shimizu135** [comment]
ありがとうございます、確認致しました
