### ISSUE TITLE
PDFファイルへリンクが張れない問題

### ISSUE THREAD

**Issue by Keita-Shimizu135** [ethereum-terakoya/ethereum-terakoya.github.io#19]
blog＞個別回＞files配下にPDFを格納して、記事からリンクを貼りたいがfile not foundとなる

**Comment by Keita-Shimizu135** [comment]
すみません、SQ優先ですがこちらhelpお願いします

**Comment by hirasaki1985** [comment]
## 対策
静的ファイルはstaticディレクトリにも置けるということで、そちらで参照するようにしました。
https://stackoverflow.com/questions/61539363/add-a-pdf-file-in-gatsby

## 行ったこと
* 「blog/id-blockchain-last/files」のPDFファイルを「/static/pdf」に移動。
*  リンクを`<a href="/pdf/1_terakoya-workshop-introduction.pdf">`に修正
* gitプロジェクト上の/static/pdfディレクトリと、a hrefの/pdfが紐づくようになる。

## 注意点
* PDFファイルは「/static」ディレクトリ配下ならどこでもよいですが、仮でpdfディレクトリを作成してそこに置きました。
* リンクをする時は`<a href="/pdf/1_terakoya-workshop-introduction.pdf">`のようにhrefの頭に/をつけてください(URLの絶対参照)。
* https://github.com/ethereum-terakoya/ethereum-terakoya.github.io/commit/49c03ed438c8806665a38347392a7f4e44f0e263#diff-dc05199cebb4599dda6abaf73b056aded0e385c9eab4cef82ba0115d19403554R60 こちらのリンク先で正常にリンクが張れていることを確認しました。
