### ISSUE TITLE
デザイン見直し検討

### ISSUE THREAD

**Issue by Keita-Shimizu135** [ethereum-terakoya/ethereum-terakoya.github.io#20]
要件：清水
デザイン・実装：伊藤さん

**Comment by Keita-Shimizu135** [comment]
現状はこのようなイメージ

[【ETHT】サイト改修方針_v001.xlsx](https://github.com/ethereum-terakoya/ethereum-terakoya.github.io/files/5573215/ETHT._v001.xlsx)

**Comment by Keita-Shimizu135** [comment]
修正

[【ETHT】サイト改修方針_v002.xlsx](https://github.com/ethereum-terakoya/ethereum-terakoya.github.io/files/5594182/ETHT._v002.xlsx)

**Comment by couger-ito** [comment]
@Keita-Shimizu135 office無いので、エクセル開けない、、、。

**Comment by couger-ito** [comment]
【マニュアル】
ファイル名、最終更新
【MNファイル】
ファイル名、最終更新
【今お得】
MN日付、キャンペーン名、開始日、終了日、最終更新
【事前発注】
MN日付、事前発注名、事前発注開始日、事前発注終了日、最終更新

**Comment by Keita-Shimizu135** [comment]
@couger-ito 
上のコメントはSQの方ですかね？

**Comment by ShumpeiSasaki** [comment]
12/11(金): デザイン案作成 - 清水さん
12/18(金): 実装完了 - 伊藤さん、平崎さん

**Comment by Keita-Shimizu135** [comment]
最終的にミニマム案になりましたので、こちらでお願いいたします

【デザイン】
現行のものを利用（変更しない）

【構成】
お知らせはヘッダーメニュー部分に含め別タブとする
⇒ワーキンググループ・お知らせ・お問い合わせ

その分、アクティビティ以降を上に繰り上げる

期限感12/15（火）でいけますでしょうか
上記対応で3時間かからない想定ですが、乖離ありましたら教えてください

**Comment by hirasaki1985** [comment]
@couger-ito 12/15日までに対応をお願いいたします。

**Comment by Keita-Shimizu135** [comment]
お知らせは伊藤さんが実装済のため、こちらの部品をヘッダーメニューに組み込めばいい想定

![localhost_8000_(Square - Note PC)](https://user-images.githubusercontent.com/73087577/102303252-239ff400-3f9e-11eb-993e-0e9507677761.png)

**Comment by Keita-Shimizu135** [comment]
@hirasaki1985 
すみませんが、宜しくお願い致します
不明な点は問合せください

（12/17対応予定）
[対応イメージ.xlsx](https://github.com/ethereum-terakoya/ethereum-terakoya.github.io/files/5701346/default.xlsx)

**Comment by hirasaki1985** [comment]
## トップページ
![image](https://user-images.githubusercontent.com/15853208/102446077-4b5f8c80-4070-11eb-829b-4f146b84f58b.png)

## お知らせ
![image](https://user-images.githubusercontent.com/15853208/102446120-5fa38980-4070-11eb-9dc6-3bfdcbd7e1f5.png)

**Comment by Keita-Shimizu135** [comment]
@hirasaki1985 
**トップページ**

について、「ワーキンググループ」以降が伊藤さんバージョンになってしまっているため、以下のものに戻していただけないでしょうか。お手数ですみません

https://ethereum-terakoya.org/

「アクティビティ」と赤いタグが付いている箇所は、centerに平文で表示していただけますか？

**お知らせ**

コンテンツはこちらで大丈夫です。
「お知らせ」のタグについては、上述のアクティビティと同じでお願いいたします

**Comment by hirasaki1985** [comment]
@Keita-Shimizu135 
修正いたしました。

> 「アクティビティ」と赤いタグが付いている箇所は、centerに平文で表示していただけますか？
こちら対応して、centerで表示してます。

ただ、元々この部分には太字などの装飾はしておらず、そのまま表示してました。(周りとの色の関係で平文じゃなくて見ていそうです)
お知らせも同様です。

## トップページ
![image](https://user-images.githubusercontent.com/15853208/102460432-4e677680-408a-11eb-8759-44bce7cc6148.png)

**Comment by Keita-Shimizu135** [comment]
@hirasaki1985 
すみません、遅くなりました
こちらでご確認頂けますか？

[【ETHT】サイト改修方針_v005.xlsx](https://github.com/ethereum-terakoya/ethereum-terakoya.github.io/files/5708316/ETHT._v005.xlsx)

**Comment by hirasaki1985** [comment]
@Keita-Shimizu135 
ただいまsourceリポジトリを更新しました。お手すきでご確認お願いいたします。
package.jsonを更新していますので、pullしたら再度yarn installをお願いします。
また、翻訳のお願いが２箇所ございまして、
## ①
https://github.com/ethereum-terakoya/ethereum-terakoya.github.io/blob/source/src/pages/news.js#L33-L47
お知らせの一覧を英語対応できるようにしておいたので、こちらに英語版を書いて更新していただきたいです。
## ②
https://github.com/ethereum-terakoya/ethereum-terakoya.github.io/blob/source/i18n/react-intl/en.json#L25
こちらはトップページのワーキンググループ「インターネット投票の実現にむけて」の英語表記になります。

**Comment by Keita-Shimizu135** [comment]
対応済、クローズ
