### ISSUE TITLE
デザイン: デザインの調整

### ISSUE THREAD

**Issue by ShumpeiSasaki** [ethereum-terakoya/ethereum-terakoya.github.io#22]
既存のデザインを大幅に変えず見栄えを調整したいです。
https://ethereum-terakoya.org/

**Comment by ShumpeiSasaki** [comment]
@Milliglam こちらお願いします。

**Comment by Milliglam** [comment]
@ShumpeiSasaki @Keita-Shimizu135 
PSDファイルを共有させていただきます！
https://www.dropbox.com/sh/i0g2eqr6py50fnz/AAD_GQbakqnj-QL2nLUZGohia?dl=0

**Comment by Keita-Shimizu135** [comment]
@hirasaki1985 
1/6目標でお願いいたします

**Comment by hirasaki1985** [comment]
@Milliglam 
PSDファイル確認させていただきました。
右側のデザインで使用しているアイコン類がほしいのですが、pngファイルかsvgファイルでまるっといただけないでしょうか？

**Comment by Milliglam** [comment]
@hirasaki1985 
アイコン類一式を書き出したものを共有します！
https://www.dropbox.com/sh/ao38ja1exyjnsqx/AAB28rK_A_w0U6Z-2HAUUqECa?dl=0

**Comment by hirasaki1985** [comment]
@Milliglam 
ありがとうございます！

**Comment by Keita-Shimizu135** [comment]
@hirasaki1985 
テストブランチ確認しました、ありがとうございます
トップ絵の寺を右に動かし、テキスト部分も右に（PSDのとおりのイメージに）したいのですが、可能でしょうか？

**Comment by hirasaki1985** [comment]
@Keita-Shimizu135 
対応してブランチを更新しております。

**Comment by Keita-Shimizu135** [comment]
@hirasaki1985 
ありがとうございます
後は微調整でいけそうですので、sourceにマージ頂けますか？

**Comment by hirasaki1985** [comment]
@Keita-Shimizu135 
souceにマージしました！

@couger-ito 
ヘッダーのメニューでコンフリクトがあったので対応しました。
マージミスがないかだけ確認お願いできますでしょうか。

**Comment by Keita-Shimizu135** [comment]
@couger-ito 
確認が終わったらこちらでコメントいただけますか？
それをもってクローズします

**Comment by couger-ito** [comment]
@Keita-Shimizu135 確認しました。大丈夫です。
