### ISSUE TITLE
contributorに各社ロゴのページを追加

### ISSUE THREAD

**Issue by Keita-Shimizu135** [ethereum-terakoya/ethereum-terakoya.github.io#25]
タイトルのとおり

**Comment by Keita-Shimizu135** [comment]
下記のイメージでお願いします。1行に4企業のロゴが入るイメージです
「XXXX」の文言は後ほど更新します（テキストが編集できればOK）
また、企業名は入れない可能性もあります（テキストがなくても違和感のない間隔にしたい）

<img width="892" alt="contributor_image" src="https://user-images.githubusercontent.com/73087577/103839577-11affd80-50d3-11eb-9ebc-b2def7ebaabe.png">

一旦、こちらのファイルでレイアウト整えて頂けますでしょうか
![symbol_mark_rgb_red](https://user-images.githubusercontent.com/73087577/103839881-b03c5e80-50d3-11eb-938f-faa7f60280d4.jpg)

こちらはすぐにsourceにマージせず、キャプチャで事前に確認させてください

**Comment by Keita-Shimizu135** [comment]
XXXXの部分、参画企業でお願いします

**Comment by Keita-Shimizu135** [comment]
英語はcontributor

**Comment by couger-ito** [comment]
![localhost_8000_ (1)](https://user-images.githubusercontent.com/74518741/103858487-c2ca8e00-50fb-11eb-9d4c-b7bd6740c335.png)

確認お願いします。

**Comment by couger-ito** [comment]
５つ目は、一段下がり、真ん中に配置されるようになっています。

**Comment by couger-ito** [comment]
![localhost_8000_ (2)](https://user-images.githubusercontent.com/74518741/103858881-7895dc80-50fc-11eb-89fd-0cb7884d2720.png)

**Comment by couger-ito** [comment]
![localhost_8000_ (3)](https://user-images.githubusercontent.com/74518741/103859420-59e41580-50fd-11eb-8c04-f0dc256e7afd.png)
左から並べたバージョン

**Comment by couger-ito** [comment]
【参画企業追加方法】
1. 画像ディレクトリ（src/contoributor/xxxx.png）にロゴ画像を追加
1. 企業名を辞書に追加（i18n/{en|ja}.json）
1. src/conponents/contoributor.js に
    1. `contributorImages`のgraphQLにロゴ画像クエリを追加
    1. `StaticQueryコンポーネント`内の`contributors`配列 に、企業名と画像のオブジェクトを追加
   
で追加されます。
