### ISSUE TITLE
デザイン-スマホ対応（ヘッダー）

### ISSUE THREAD

**Issue by Keita-Shimizu135** [ethereum-terakoya/ethereum-terakoya.github.io#35]
・上の赤枠
メニューの間隔が狭くタップしづらい
間隔（line-height？）はを広げたい
お問い合わせと言語アイコンはそのままでは違和感があるので、「お知らせ」と同じプレーンなテキストにできますか？

・下の赤枠
スマホ（iPhone8）では寺が出ないので、いっそ黒背景にアイコンとテキストをtext-aligh="center"で表示したい

![Image from iOS (3)](https://user-images.githubusercontent.com/73087577/104711551-dc577f80-5764-11eb-87e4-b8e8bc8ad723.png)

ツールチップも同様に、タップ領域が狭いので行間を開けたい

![Image from iOS (2)](https://user-images.githubusercontent.com/73087577/104711629-f42f0380-5764-11eb-8e93-6cef3e5db624.png)

**Comment by couger-ito** [comment]
![スクリーンショット 2021-01-18 160359](https://user-images.githubusercontent.com/74518741/104882724-e36dd000-59a6-11eb-96a7-56e4f665ba5e.png)
![スクリーンショット 2021-01-18 160523](https://user-images.githubusercontent.com/74518741/104882782-00a29e80-59a7-11eb-8120-e290dd0ced41.png)

こんな感じでどうでしょうか？

寺画像の件ですが、
あと、私の方では、寺画像が表示されていました。
後ほどコミットしたときに再度寺画像の確認いただけますか？

**Comment by Keita-Shimizu135** [comment]
@couger-ito 
大丈夫です、ありがとうございます
「日本語/English」をクリックした場合も、ツールチップが出る挙動でよいでしょうか

**Comment by couger-ito** [comment]
> @couger-ito
> 大丈夫です、ありがとうございます
> 「日本語/English」をクリックした場合も、ツールチップが出る挙動でよいでしょうか

@Keita-Shimizu135 
それぞれの言語のTOPページへの、テキストリンクとなっております。
（例えば）`言語`をクリックして、ドロップダウンから、言語を選択。みたいな形をイメージしてましたでしょうか？

**Comment by Keita-Shimizu135** [comment]
@couger-ito 
挙動はそれで大丈夫です

ただ、寺は出てこないので、アイコン・テキストの中央寄せか、寺が出るよう調整をお願い致します
端末がiPhone8という以外の情報が必要でしたら、仰ってください

**Comment by couger-ito** [comment]
@Keita-Shimizu135 
寺画像が出ない原因がわからなかったので、
アイコン・テキストの中央寄せで対応しました。
